import Head from "next/head";
// add bootstrap css
import "bootstrap/dist/css/bootstrap.css";
import Link from "next/link";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import logoKings from "../assets/logoKings.svg";

export default function Home() {
  return (
    <>
      <Head>
        <title>Kings Radio - Lo que quieres escuchar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={`row ${styles.nav} d-flex align-items-baseline`}>
        <div className="col-sm-1 col-xs-12">
        <Image src={logoKings} alt="Logo Kings Radio" />
        </div>
        <div className={`col-sm-10 col-xs-12 ${styles.fonts_nav}`}>
          <Link href="/">Nosotros</Link>
          <Link href="/">Contacto</Link>
          <Link href="/">Ventas</Link>
      </div>
      </div>

      <div className={`row ${styles.header}`}>
        <div className="col-12">
          <h1>Ahora sonando</h1>
        </div>
      </div>
      <div className={`${styles.card_playList}`}>
        <p>Foto</p>
        <p>Botones de Reproductor</p>
        <p>social media</p>
        <p>Nombre locutor</p>
      </div>
      <div className="row events">
        <div className="col-12">
          <h2>Soy Eventos</h2>
        </div>
      </div>
      <div className="row programs">
        <div className="col-12">
          <h2>Soy Programas</h2>
        </div>
        <div className="row dj">
          <div className="col-12"></div>
        </div>
        <div className="row sponsors">
          <div className="col-12">
            <h2>Soy Patrocinador</h2>
          </div>
        </div>
        <div className="row topTen">
          <div className="col-12">
            <h2>Soy TopTen</h2>
          </div>
        </div>
      </div>
      <footer></footer>
    </>
  );
}
